# Config file for https://travis-ci.org/

language: node_js
node_js:
  - "9"

install:
  - npm install
  - npm install -g codecov

script:
  - npm run test:coverage && codecov

# Monitor only these branches
branches:
  only:
  - master