# Config file for https://travis-ci.org/

language: node_js
node_js:
  - "9"

install:
  - npm install

script:
  - npm run test

# Monitor only these branches
branches:
  only:
  - master